### ISSUE TITLE
What is the difference between Invocable-Interoperable-Harmonized Network Spatial Data Services?

### ISSUE THREAD

**Issue by InspireGeo** [INSPIRE-MIF/helpdesk#25] opened 2020-10-08 07:38 UTC
First off all, I should understand what is exactly different with;

• Not invocable SDS 
• Invocable SDS
• Interoperable SDS
• Harmonised SDS 
• Network services 

If someone has proper documentation I will be very grateful ..

Best Regards

**Comment by MarcoMinghini** [comment] 2021-03-31 12:38
This issue was originally opened in the [Validator helpdesk](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/). We moved it here, since it addresses a more general INSPIRE discussion topic and is not Validator-specific.

**Comment by iuriemaxim** [comment] 2021-03-31 20:43
This question is still open as it is not clear and others have similar questions https://github.com/INSPIRE-MIF/helpdesk/issues/1

**Comment by heidivanparys** [comment] 2021-05-13 10:27
> 
> 
> First off all, I should understand what is exactly different with;
> 
> • Not invocable SDS
> • Invocable SDS
> • Interoperable SDS
> • Harmonised SDS
> • Network services
> 

@InspireGeo 
I created the following [Euler diagram](https://en.wikipedia.org/wiki/Euler_diagram) that hopefully can shed light on the different kinds of services (the original diagram in SVG format, with clickable links, is available [here](https://raw.githubusercontent.com/heidivanparys/inspire/main/figures/services%20Euler%20diagram.svg))

![services Euler diagram](https://user-images.githubusercontent.com/11427611/118107859-93949800-b3df-11eb-8fed-cf61047d7d2b.png)

It is not an officially approved figure, but it reflects my view on this. Some supplementary information:

1. The concept "spatial data service" is not specific to INSPIRE. In ISO TC/211 it is usually called "[geographic information service](https://isotc211.geolexica.org/concepts/206/)", but it means the same really. So that is why there is a box named "_INSPIRE_ spatial data service" on the diagram.
2. The concepts "discovery service", "view service", "download service", "transformation service" and "invoke service" are not specific to INSPIRE. It is a categorisation of services based on the categorisation scheme "usage life cycle" (so a user would first discover a data set, then visualize it, then download it, then do even more advanced stuff, etc.) This is recognised in the [current edition of ISO 19119](https://www.iso.org/obp/ui/#iso:std:iso:19119:ed-2:v1:en): "services shall be categorised according to a service taxonomy based on architectural areas† and may also be categorised according to a usage life cycle perspective‡, as well as according to domain specific and user defined service taxonomies, providing support for publication and discovery of services". So this is why e.g "discovery service" and "INSPIRE spatial data service" _overlap_, instead of the "discovery service" being _contained in_ "INSPIRE spatial data service".
3.  I would argue that the concepts "discovery service", "view service", "download service", "transformation service" and "invoke service" are by no means specific to the geographic information domain. The same kinds of services can be identified for other domains (perhaps they are called something else, but basically it is the same): e.g. statistical data can be discovered in a portal viewed/visualised as charts, downloaded as CSV files, etc. So this is why e.g "discovery service" and "spatial data service" _overlap_, instead of the "discovery service" being _contained in_ "spatial data service".
4. "network service" is on the other hand an INSPIRE-specific concept. The term "network service" is used in other contexts, but with a different meaning.
5. "network service" and "invocable spatial data service" are [disjoint](https://en.wikipedia.org/wiki/Disjoint_sets), an INSPIRE spatial data service is either a network service or an invocable spatial data service, an INSPIRE spatial data service cannot be both. The IR interoperability of spatial data sets and services states this clearly in [article 1](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231&from=EN#tocId3): "This Regulation does not apply to the network services falling within the scope of Commission Regulation (EC) No 976/2009"
6. A "harmonised spatial data service" _is a kind of_ "interoperable spatial data service", therefore a "harmonised spatial data service" _is contained in_ "interoperable spatial data service" on the diagram.

† That is the classification referred to [here](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224#tocId80) in the IR metadata and also available [here](https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory).
‡ If you have access to [ISO 19116:2016](https://www.iso.org/obp/ui/#iso:std:iso:19119:ed-2:v1:en): see section 10.11, User-perspective Lifecycle model for Services

**Comment by heidivanparys** [comment] 2021-05-13 10:57
> I am also interested to get a proper response and not just to be pointed to the TGs of the SDS that are not explicit on what a data provider should do in order to have a harmonised SDS, besides on how to fill the metadata. I am just curious if a Harmonised SDS is not actually a Download Network Service.
> I am curious why it was made this split NS vs SDS, that had as consequence the elimination of the WPS while playing with the words invoke & invocable and confusion was introduced starting from this schema [...]:

@iuriemaxim
The comment above and the diagrams hopefully answer your questions:

- No, a harmonized spatial data service is not a download network service
- WPS is not eliminated as far as I can see. I have no experience with WPS, but depending on the exact processes it implements, I guess a specific installation could be categorised
  - as a [transformation service](http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/transformation)
  - as an [invoke service](http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/invoke)
  - as a [service that is neither a discovery, view, download, transformation or invoke service](http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/other).

![image](https://user-images.githubusercontent.com/11427611/118115782-af04a080-b3e9-11eb-8aa5-8dcfe0e519db.png)

![image](https://user-images.githubusercontent.com/11427611/118115628-7cf33e80-b3e9-11eb-9159-e14fa9925b71.png)

**Comment by KathiSchleidt** [comment] 2021-05-13 11:23
Many thanks for the diagrams and descriptions, I've also often been down this road of trying to figure out what are the NS (the 5 types listed: discovery, view, download, transformation, invoke), thus by process of elimination determining that the delta left over must be SDS. But, I don't find anything :( Going through the list and adding examples, I come to the following:

- discovery: Catalogue services, e.g. CSW
- view: seems to default to WMS in all cases
- download: here we have a rich set of approved service types, WFS, WCS, SOS, OAPIF, STA
- transformation: assuming WPS, could also include WCPS, but haven't yet seen utilized in INSPIRE
- invoke: ah... this is where I already start getting lost, I'm familiar with invoking services, but am a bit at a loss as to what an invoke service itself would actually be. Working assumption is that this has to do with orchestration, chaining various of the services above within a workflow, but never really confirmed, less seen in operation

However, that brings me to the end of my potential service types (probably due to my lack of understanding) - could somebody please provide a concrete example of what a SDS would actually be? Something other than the often repeated process of elimination pointing to "the rest"?

Actually, the best (albeit politically incorrect ;) ) explanation I've received over the years on both the Invoke and SDS is that these are actually artifacts of the legal transposition of the text - the lawyers involved not familiar with the terminology doing their best to make English legal text from the various technical plans - somehow the words Invoke Service and Spatial Data Service made sense in this process, was never technically challenged. Ever since, brave souls have been searching for a technical content for these legal artifacts. May just be a rumor, but made more sense than anything else I've heard to date! ;)

**Comment by iuriemaxim** [comment] 2021-05-13 19:18
Dear @KathiSchleidt and @heidivanparys thank you very much for the clarifications. I have the same or almost the same understanding,
But first I would like to ask a simple question: Can WMS or WFS (that serves as spatial dataset that is in th scope of INSPIRE, i.e, coressponds to one/multiple INSPIRE Data theme) be an invocable SDS?
I have the same problem as pointed by Kathy:, but I will reformulate a little bit: Can samone provide a concrete example of what an invocable SDS would actually be, if it is disjoined to the network service?

Here is the answer to the above question :) : 
https://inspire.ec.europa.eu/id/document/tg/sds/4.0/examples

I am almost sure that the TG from 2016 (https://inspire.ec.europa.eu/id/document/tg/sds) created a lot of confusion by disjoining the datasets from services, while defining Interoperable SDS that are not Network services.
If so, what are they? An FTP server is an interoperable SDS? Or maybe a Google Drive or OneDrive folder?

Related to the lawyers involved, I also read the text of the INSPIRE Directive. There is no single article which stipulates that the serrvices should be either network services, either should be invocable/interoperable/harmonsided.

Invocability, interoperability and harmonisation refers actually both to the the data and to the services. There are a lot of network services that are neither interoperable, neither the data that is served by them is harmonised. But they are network services. Therefore I cant figure why it was decided that a service could be either a network service, either an invocable/interoperable/harmonsised or even another SDS (whatever this could mean if disjoined).

Can someone indicate the Article in the INSPIRE Directive from where it is clear that network services should be disjoined to the invocable/interoperable/harmonised/other SDS and why they cant overlap ?

**Comment by iuriemaxim** [comment] 2021-05-13 19:53
@heidivanparys 

![image](https://user-images.githubusercontent.com/20813598/118178525-b7d29200-b43c-11eb-840b-b32b76ef97bb.png)

Thank you for the image that reflects the TG from 2016,

I can imagine one invocable SDS that is neither an discovery/view/download/transformation/(invoke): Sending an email to an email address from where an institution is responding with the dataset, while both the dataset and the service are described trough INSPIRE valid metadata. Should this be considered as an example?

I have a certain problem to understand the 5th one (non-invocable SDS). Proabbly the same service as the above one, but where the Metadata is not valid or the metadata is valid but the email or phone number where to make the request os not provided, so the user should search for this information on Google by knowing the name of the data provider. Could this be considered as an example?

**Comment by iuriemaxim** [comment] 2021-05-13 20:09
@InspireGeo or @carlospzurita Please re-open this "discussion".

**Comment by iuriemaxim** [comment] 2021-05-14 06:44
@KathiSchleidt

I can provide some clear examples of "invoke" service easy to be understood, considering that they are WPS according to these documents:
https://inspire.ec.europa.eu/documents/Network_Services/Technical_notes_inspire_invoke_services.pdf
https://inspire.ec.europa.eu/documents/Network_Services/NSDT_PositionPaper_IR_Invoke_Services_v1.0.pdf
and to the Geoserver documentation
https://docs.geoserver.geo-solutions.it/edu/en/inspire/intro.html

Trough an Invoke service a user could determine:
- the percentage of each category of protected sites (protected areas) in each administrative unit by invoking two services, one that provides access to the protected sites (PS) and another one that provides access to administrative units (AU). The inwoke service will require the two WFS requests or the two datasets in GML format and will return a file with the results (could be either a GML, an XML, CSV or Excel file)
- determine the maximum, minimum, average and standard deviation of the distances between meteorological stations and/or determine the areas where there the distance to any meteorogical station is larger than 50 km, in this case only one service should be invoked (EF), by providing the request that returns the position of meteorological stations
- Determine the total length of various types of roads in a country or in a certain area.
- Determine the lenght of the roads that are crossing and are within protected areas.
- Determine the total area of forests within all and each protected areas by invoking Land Cover and Protected Sites.
- Determine the total area loss/increase of forests within all protected areas in the last 20 years.
- Determine the number of buildings in the Natural Risk Zones of a certain category (i.e. flooded areas)

**Comment by heidivanparys** [comment] 2021-05-14 07:27
@KathiSchleidt 

> invoke: ah... this is where I already start getting lost, I'm familiar with invoking services, but am a bit at a loss as to what an invoke service itself would actually be. Working assumption is that this has to do with orchestration, chaining various of the services above within a workflow, but never really confirmed, less seen in operation

I also think that the original idea had to do with [workflow engines](https://www.iso.org/obp/ui#iso:std:iso:12651:-2:ed-1:v1:en:term:3.50). I found at least two documents that mention BPEL: https://kortforsyningen.dk/sites/default/files/old_gst/DOKUMENTATION/Data/Emigreret_fra_www2/Kortforsyningsseminar2009/KFseminar2009_AFC_geoportal.ppt says "invoke: Enables and controls the execution of spatial data services; Business Process Execution Language (BPEL)" (slide 18) and http://inspire.ec.europa.eu/documents/Network_Services/Technical_notes_inspire_invoke_services.pdf also mentions "workflow engine" and "BPEL" a few times

> However, that brings me to the end of my potential service types (probably due to my lack of understanding) - could somebody please provide a concrete example of what a SDS would actually be? Something other than the often repeated process of elimination pointing to "the rest"?

The classification from ISO 19119 can give some inspiration, see also https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory. E.g. a feature generalisation service could be a good candidate.

> Actually, the best (albeit politically incorrect ;) ) explanation I've received over the years on both the Invoke and SDS is that these are actually artifacts of the legal transposition of the text - the lawyers involved not familiar with the terminology doing their best to make English legal text from the various technical plans - somehow the words Invoke Service and Spatial Data Service made sense in this process, was never technically challenged. Ever since, brave souls have been searching for a technical content for these legal artifacts. May just be a rumor, but made more sense than anything else I've heard to date! ;)

My personal opinion is that proper clarification of concepts and terms, ánd documenting all that in a glossary of some sort, should be done before legislation enters into force, as we here see the consequences of not doing so. See e.g. https://en.digst.dk/policy-and-strategy/digital-ready-legislation/ and https://en.digst.dk/media/20206/en_guidance-regarding-digital-ready-legislation-2018.pdf (principle 4: Consistency across authorities - uniform concepts and reuse of data).

**Comment by heidivanparys** [comment] 2021-05-14 07:52
@iuriemaxim 

> But first I would like to ask a simple question: Can a WMS or WFS (that serves as spatial dataset that is in th scope of INSPIRE, i.e, coresponds to one or multiple INSPIRE Data themes) be an invocable SDS?

A WMS is a view service, a WFS is a download service. So those services are network services, not invocable spatial data services.

> I have the same problem as pointed by Kathy, but I will reformulate a little bit: Can somebody provide a concrete example of what an invocable SDS would actually be, if it is disjoined to the network service?

The classification from ISO 19119 can give some inspiration, see also https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory. E.g. a feature generalisation service could be a good candidate.

> Related to the lawyers involved, I also read the text of the INSPIRE Directive. There is no single article which stipulates that the serrvices should be either network services, either should be invocable/interoperable/harmonsided.
> 
> [...]
> 
> Can someone indicate the Article in the INSPIRE Directive from where it is clear that network services should be disjoined to the invocable/interoperable/harmonised/other SDS and why they cant overlap ?

Please note that the implementing rules are also legally binding, see also the figure below. So the relevant legally binding text is [article 1 in the IR ISDSS](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231&from=EN#tocId3) (Regulation 976/2009 being the IR NS):

> This Regulation does not apply to the network services falling within the scope of Commission Regulation (EC) No 976/2009

![Relationship between legislation and TGs](https://inspire.ec.europa.eu/sites/default/files/statesgraficd-4.png)

> Thank you for the image that reflects the TG from 2016

As I said, the image reflects as how I see it, so I cannot guarantee it is a 100% correct, but the idea was that it should reflect what is said in the legislation (Directive plus Implementing Rules). Which is why the diagram includes "invoke service", although https://inspire.ec.europa.eu/id/document/tg/sds does not have "invoke service" in its diagram.

> I have a certain problem to understand the 5th one (non-invocable SDS). Probably the same service as the above one, but where the Metadata is not valid or the metadata is valid but the email or phone number where to make the request os not provided, so the user should search for this information on Google by knowing the name of the data provider. Could this be considered as an example for a non-invocable SDS?

(I corrected the previous diagrams to say "INSPIRE SDS that is not a Network service and not an invocable SDS" instead of "non-invocable SDS").
The [IR ISDSS](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231&from=EN#tocId4) states:

> ‘Invocable spatial data service’ means all of the following:
> 
> (a) a spatial data service with metadata which fulfils the requirements of Commission Regulation (EC) No 1205/2008 ( 3 ),
> (b) a spatial data service with at least one resource locator that is an access point,
> (c) a spatial data service in conformity with a documented and publicly available set of technical specifications providing the information necessary for its execution

My guess is that it is point b and c that are important here. So if there e.g. is an INSPIRE spatial data service, that is not a network service, and without specification, so without the information necesary for its execution for an external user, then that external user cannot actually use that service, hence the service is non-invocable. Perhaps an analogue service or a service that involves sending a mail would fit here as well, but I would ask for a second opinion here.

**Comment by heidivanparys** [comment] 2021-05-14 08:30
> So, the chart maybe should be adjusted by deleting the "invoke" services if not looking only at the Inspire Directive and understading that "invoke" was transformed into "invocable" in order to create this new category of invocable/interoperable/harmonised/other SDS, instead of aknowledge that Network Services (as well as the datasets served by them) could be either invocable, interoperable or harmonised and that "invoke" services are "WPS".

The terminology can be confusing indeed. "invocable spatial data service" in an INSPIRE context should not be understood as "normal" English (so as in "spatial data service that can be invoked") but should be understood as defined in [article 2 of the IR ISSDS](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231&from=EN#tocId4). "invocable non-network service" would be closer to "normal" English I guess, at least for the "invocable" part. But we have to stick to the terms in the current legislation.

The same reasoning goes for the other terms (interoperable, harmonized).

But I don't agree that "invoke" was transformed to "invocable".

> This means that discovery network services need to provide access also to the additional SDS metadata elements, which contain, among other things, information necessary for the invocation of SDS. Through the provision of these metadata additional elements, the obligation to provide (network) “services allowing spatial data services to be invoked” is being fulfilled.

I don't know the background for this formulation in https://inspire.ec.europa.eu/id/document/tg/sds. @alexanderkotsev @michellutz  Who could provide more info about this? Is it perhaps just meant as a clarification that, for a given dataset, an "invoke service" associated to that data set does not necessarily have to exist (in contrary to a download service: it must always be possible to download that data set)? And _if_ a data provider has established a workflow engine on one or more INSPIRE spatial data sets, then that service is an INSPIRE spatial data service, it has type "invoke service", and it must be compliant with the IR metadata and IR network services.

For the transformation services, such a clarification is already in the Directive: "Spatial data sets shall be made available in conformity with the implementing rules **either** through the adaptation of existing spatial data sets **or** through the transformation services referred to point (d) of Article 11(1)."

**Comment by KathiSchleidt** [comment] 2021-05-14 10:20
@heidivanparys I love the idea of requiring clear definitions for all relevant terms BEFORE finalization of a legal act!

I just checked [IATE ](https://iate.europa.eu/home) to see if similar definitions existed from other legislation, but all comes from the known bits around INSPIRE and it's followup regulations.

Alternatively, as this issue has caused a great deal of confusion for a long time now, do you think it could be possible to get extended definitions (e.g. on invoke services more than `service that allows defining both the data inputs and data outputs expected by the spatial service and a workflow or service chain combining multiple services`, still reads close to a processing service) together with examples somewhere on the official [INSPIRE pages](https://inspire.ec.europa.eu/). I believe such clarification would save many people much time!

**Comment by iuriemaxim** [comment] 2021-05-14 17:48
Dear @heidivanparys, the answer is really helpful.

> The classification from ISO 19119 can give some inspiration, see also https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory. E.g. a feature generalisation service could be a good candidate.

Indded now I can identify in the https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory some SDS that cant be considered network services. Hovever a feature generalisation is still a transformation service, so it is a network service, isn't it?
But services such as the following ones indeed do not seems to be Network Services,:
- Order handling service
- Standing order service
- Registry Service
- Subscription service
- Messaging service
- Remote file and executable management
- Geographic feature editor
- Geographic spreadsheet viewer
- Geographic symbol editor
- Geographic viewer
- Service editor

All that are clasified as Geographic Processing Service, I think that are falling inside transformation services and invoke services, or at least can be implemented trough OGC WPS.

But indded there are services listed there that are not Network Services.

I have a problem in identifying which one are or could be considere invovable, interoperable or harmonised and which ones fall into "other SDS" category. So please provide some guidance.

I have also a problem to classify these ones as being SDS according to this decision block, by in some cases I can imagine, but this is stil unclear to me. Any comments are welcomed.

![image](https://user-images.githubusercontent.com/20813598/118308564-c5e3e980-b4f4-11eb-9083-a32fded84779.png)

I understand then that the INSPIRE Registry falls into SDS category. Is this correct?

I have also a problem understanding what should be done to an SDS that is invocable in order to make it interoperable or harmonised:

![image](https://user-images.githubusercontent.com/20813598/118308970-4a366c80-b4f5-11eb-9d8d-70b60a8a200b.png)

Can the INSPIRE Registry become interoperable or harmonised?

Can be provided an exanple of an interoperable and harmonised SDS?

Thank you for the clarifications,
Iurie

**Comment by KathiSchleidt** [comment] 2021-05-14 18:16
to `Can the INSPIRE Registry become interoperable or harmonised?`

I just compared the 2 INSPIRE metadata-codelists:

- [Spatial data service type](https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType): List of the well known Network Services plus "Other"
- [Classification of spatial data services](https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory): 78! different types of potential services 

The first codelist would actually imply that Spatial Data Services **ARE** Network Services (or are the SDS the Other?), while the 2nd blows my mind! Apart from clarifying what the first codelist implies pertaining to NS vs. SDS, I'd really like a matrix of the 78 entries from the classification to the service types (with or without SDS ;) )

**Comment by iuriemaxim** [comment] 2021-05-14 18:51
Hi @KathiSchleidt,

`The first codelist would actually imply that Spatial Data Services ARE Network Services (or are the SDS the Other?), while the 2nd blows my mind! Apart from clarifying what the first codelist implies pertaining to NS vs. SDS, I'd really like a matrix of the 78 entries from the classification to the service types (with or without SDS ;) )`

Here I can provide some insights:
All that are listed as "Geographic Processing Service" fall into Network Services, either into "transformation service" or into "invoke service" category.

An exammple of a "Feature access service" is the WFS
An example of a "Map access service" is a WMS
An example of a "Coverage access service" is a WCS
An example of a "Catalogue service" is a CSW

So almost sure all the above and the "Geographic Processing Service" are "Network Services".

I have a problem to clarify if a "Gazetter service" is a "Network Service" or not, but maybe with very few exceptions all the other falls into "Other category" of the "Network Services", so my understandis is that they are not "Network Services".

I cant see however how the rest of the services in the list could become interoperable or harmonsied (where applicable), as the IR is requesting this.

**Comment by iuriemaxim** [comment] 2021-05-17 06:33
Dear @KathiSchleidt I raised a question to the INSPIRE Registry Helpdesk in order to clarify the content of the Spatial Data Services Codelist.

Question is here:
https://github.com/INSPIRE-MIF/helpdesk-registry/issues/19

**Comment by iuriemaxim** [comment] 2021-05-17 06:42
By Reading the

**Comment by KathiSchleidt** [comment] 2021-05-17 07:59
@iuriemaxim 

To your point 6 above on utilizing OData, for OGC SensorThings API we do, and are now endorsed as an official [INSPIRE Good Practice](https://inspire.ec.europa.eu/good-practice/ogc-sensorthings-api-inspire-download-service) 
However, for the wider feature world, looks like [OGC API - Features](https://inspire.ec.europa.eu/good-practice/ogc-api-%E2%80%93-features-inspire-download-service) is the accepted way forward. A bit sad as doesn't have all the rich query options of OData and STA, but to each their own (we can now extend STA with other spatial features, keeping the OData power)

Thus both of these APIs now qualify as INSPIRE Download Services (same applies to [SOS](https://inspire.ec.europa.eu/id/document/tg/download-sos) and [WCS](https://inspire.ec.europa.eu/id/document/tg/download-wcs) - only bit missing on WCS are the data models, now also mostly sorted via the [Coverage Good Practice](https://inspire.ec.europa.eu/good-practice/ogc-compliant-inspire-coverage-data-and-service-implementation)

What IS missing is a plan on how to make these similar but different OGC APIs interoperable, one of the many cool outputs of the [API4INSPIRE project](https://datacoveeu.github.io/API4INSPIRE/)

**Comment by iuriemaxim** [comment] 2021-05-17 08:12
@KathiSchleidt This is exactly what I mean, that interoperability and harmonisation is not a characteristic for "Other" Spatial Services, but they are characteristics of Network Services.

And indeed in the first instance I thougt to include in point 6 the WPS, but I just thought that SensorThings API is a better example for people to understand.

This can be read as well in order to understand various positions, as there are data provides that claim that the datasets that are served trough Network Services shuld not be valid (should bot be interoperable/harmonised): https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39

So for me it was clear even from 2016 that the TG and IR for Interoperability was wrongly designed. But as we are approaching the 2021 last deadline in implementing the INSPIRE Directive, it should be clarified that legaly there are no "Other" SDS, than Network Services. Alternatively, if data providers are required to transform the "invocable" SDS into interoperable or where practical harmonised SDS, then it should be very clear what are these invocable services that should be transformed into interoperable/harmonised services.

So the question remains opened.

**Comment by heidivanparys** [comment] 2021-05-17 08:15
> 
> I just compared the 2 INSPIRE metadata-codelists:
> 
> * [Spatial data service type](https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType): List of the well known Network Services plus "Other"
> 
> * [Classification of spatial data services](https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory): 78! different types of potential services
> 
> 
> The first codelist would actually imply that Spatial Data Services **ARE** Network Services (or are the SDS the Other?) [...]

@KathiSchleidt How to you come to that conclusion?

"spatial data service" is a generic concept, not an INSPIRE-specific concept, see the definition in [article 3 of the INSPIRE Directive](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02007L0002-20190626&from=EN#tocId6).

A network service is a spatial data service that is in the scope of INSPIRE and that is one of the following:

- discovery service
- view service
- download service
- transformation service
- invoke service

So a network service is a kind of spatial data service.

On the other hand, a spatial data service that is in the scope of INSPIRE is not necessarily a network service.

A spatial data service that is in the scope of INSPIRE and that is not a network service - thus a service that is located in the grey area on the figure below -, must have metadata element "spatial data service type" set to http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/other

![other - spatial data service type](https://user-images.githubusercontent.com/11427611/118453481-8fc28780-b6f7-11eb-8651-d97f8494476c.png)

Some confusion may arise from the following in https://inspire.ec.europa.eu/id/document/tg/sds:

> Those SDS that are not network services, but fulfil the requirements of Commission Regulation (EC) 1205/2008, have at least one resource locator and follow a publicly available technical specification are called _invocable spatial data services_. All invocable SDS shall meet the requirements specified in [**INS ISDSS**]. All other SDS are referred to in this document as _other_ SDS.

The "other SDS" as described in https://inspire.ec.europa.eu/id/document/tg/sds is a service located in the light blue area on the figure below.

![other - non-network and non-invocable](https://user-images.githubusercontent.com/11427611/118454421-a3bab900-b6f8-11eb-9138-7120b10d95b8.png)

So the "other" in http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/other _is not the same_ as "other" in https://inspire.ec.europa.eu/id/document/tg/sds, the "other service" in http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/other _is broader_ than "other SDS" in https://inspire.ec.europa.eu/id/document/tg/sds.

All the following kinds of services will have metadata element "spatial data service type" set to http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/other:

- invocable SDS
- interoperable SDS
- harmonised SDS
- non-invocable and non-network INSPIRE SDS

**Comment by heidivanparys** [comment] 2021-05-17 08:21
> Hovever a feature generalisation is still a transformation service, so it is a network service, isn't it?

@iuriemaxim I don't know how the text of the Directive should be interpreted. As always, the definition should be checked before assuming anything just from the term. [It says](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02007L0002-20190626&from=EN#tocId17) (highlighting is mine): "transformation services, enabling spatial data sets to be transformed **with a view to achieving interoperability**"

I am not sure whether feature generalisation can be categorized as a service that transforms data "with a view to achieving interoperability". I would say the goal of  a feature generalisation is a different goal. But again, I am not a legal expert, these are just my thoughts.

**Comment by heidivanparys** [comment] 2021-05-17 08:33
A general comment: metadata for all data sets and service on the INSPIRE Geoportal can be browsed via the "[Resource browser](https://inspire-geoportal.ec.europa.eu/proxybrowser/)"

![image](https://user-images.githubusercontent.com/11427611/118457884-80910900-b6fa-11eb-9eac-647e3a384d8e.png)

There you can see [what services](https://inspire-geoportal.ec.europa.eu/proxybrowser/#fq=spatialDataServiceType%3Aother&q=*%3A*) were classified by the member states as http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/other

![image](https://user-images.githubusercontent.com/11427611/118458158-bcc46980-b6fa-11eb-8418-2c98d1a60f3b.png)

If you e.g. narrow the results down to "humanInteractionService", you'll find the metadata of the [Arctic SDI portal](https://geoportal.arctic-sdi.org/).

![image](https://user-images.githubusercontent.com/11427611/118458381-fb5a2400-b6fa-11eb-8299-b5717d6336f3.png)

![image](https://user-images.githubusercontent.com/11427611/118458608-3bb9a200-b6fb-11eb-9702-f23d76c3bf09.png)

**Comment by iuriemaxim** [comment] 2021-05-17 18:38
@heidivanparys
Lets take one by one:
INSPIRE Directive is defining
‘spatial data services’ means the operations which may be performed, by invoking a computer application, on the spatial data contained in spatial data sets or on the related metadata;

If this is the definition, then the "registry service" is an SDS? Personally I cant understand why it could be as there is no spatial data contained in spatial datasets on which the server operates, neither a related metadata to these spatial datasets. Many other SDS from the 78 records in the INSPIRE Registry are also not operating on a spatial dataset, so they are not SDS according to INSPIRE definition.

There is no legal text which is listing the 78 items from the INSPIRE Registry as being SDS according to INSPIRE definition.

**Comment by iuriemaxim** [comment] 2021-05-17 22:17
@KathiSchleidt I raised a second batch of questions at the INSPIRE Registry, now related to the Spatial Data Service Type Codelist here: https://github.com/INSPIRE-MIF/helpdesk-registry/issues/20

**Comment by heidivanparys** [comment] 2021-05-21 12:48
@InspireGeo As you are the original author of this issue: I hope that the explanation in https://github.com/INSPIRE-MIF/helpdesk/issues/25#issuecomment-840468560 on your question on the difference between the different kinds of services has been answered sufficiently.

Follow-up on the discussion here:

- The aforementioned diagram is an unofficial diagram, but I can explore the options to get the approval of the MIG(-T) on this or a similar diagram for inclusion into more official documentation, if needed.
- I can also explore the options for at some point updating the [Technical Guidance for INSPIRE Spatial Data Services and services allowing spatial data services to be invoked](https://inspire.ec.europa.eu/id/document/tg/sds) in order to clarify what was discussed at https://github.com/INSPIRE-MIF/helpdesk/issues/25#issuecomment-842118830
- Some of the questions raised here are raised as separate issues: #26, https://github.com/INSPIRE-MIF/helpdesk-registry/issues/19 and https://github.com/INSPIRE-MIF/helpdesk-registry/issues/20 and follow-up should occur there.

**Comment by iuriemaxim** [comment] 2021-05-22 18:43
@heidivanparys 
Can we conclude than that "spatial data services" as defined by the INSPIRE Directive are operations such as GetCapabities, GetFeature, GetMap, etc?

**Comment by iuriemaxim** [comment] 2021-05-27 22:45
As first I tried to clarify that this is not correct at all:
"spatial data service" is a generic concept, not an INSPIRE-specific concept, see the definition in article 3 of the INSPIRE Directive.

I can analyse the next:
`A network service is a spatial data service`

In the article 3 of the INSPIRE Directive exist the following definition "‘spatial data services’ means the operations which may be performed, by invoking a computer application, on the spatial data contained in spatial data sets or on the related metadata;"

Therefore `A network service is a spatial data service` would mean that:

"A network service" is "the operations which may be performed, by invoking a computer application, on the spatial data contained in spatial data sets or on the related metadata".

The above sentence does not seems to be correct. Correct could be that "A network service is a service". And the word "service" is used alone in the INSPIRE Directive many times.

According to OGC SA could be also correct "A network service is a geographic service" and "Network services are part of geographic model/information management services"

A "network service" is **not** a "spatial data service" according to the INSPIRE Directive.

Both "network service" and "spatial data service" are not generic concepts, but concepts that are used ONLY in the INSPIRE Directive context.

**Comment by heidivanparys** [comment] 2021-05-28 15:42
@iuriemaxim 
I am not in a position to draw any final conclusions on this topic. I would be happy to bring the discussion on [this comment](https://github.com/INSPIRE-MIF/helpdesk/issues/25#issuecomment-840468560)'s diagram and underlying assumptions to the MIG-T and try to seek to a consensus diagram and final conclusions, as also proposed in https://github.com/INSPIRE-MIF/helpdesk/issues/25#issuecomment-845926742.

In order to keep the overview I would like to close this issue soon, if @InspireGeo 's question has been answered sufficiently, and follow-up on the different topics touched upon here as proposed in https://github.com/INSPIRE-MIF/helpdesk/issues/25#issuecomment-845926742 (that is, follow-up in separate issues).

**Comment by KathiSchleidt** [comment] 2021-05-29 09:08
@heidivanparys as we've been through this discussion time and time again, manage to reach some educated assumptions but never get these confirmed, I think many people would appreciate some more formal clarification/confirmation on these theories - otherwise we'll be back to this discussion next year! To my view, this service type topic would warrant a dedicated page, ideally including your diagram, maybe also explaining the difference between Network Services, Spatial Data Services, the various classifications of Spatial Data Services mentioned [above](https://github.com/INSPIRE-MIF/helpdesk/issues/25#issuecomment-841417895)

Think you could bring this to the MIG-T?

**Closed** 2021-05-31 08:48 UTC
Labels: discussion
